# Mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/resumebuilder_v2

# Email configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=8a2d88002@smtp-brevo.com
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=bushansc@gmail.com

# Application info
app.base.url=http://localhost:8080

# Cloudinary information
cloudinary.cloud-name=dhadf5h7j
cloudinary.api-key=829542913139845
cloudinary.api-secret=${CLOUDINARY_APISECRET}

# JWT Configuration
jwt.secret=your-secret-key-here-change-this-in-production-with-more-secure-and-complicated-key
jwt.expiration=604800000

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration